2020-04-26 06:31:09,157:INFO:------------------------------------------------------------------------------------------------
2020-04-26 06:53:13,764:INFO:------------------------------------------------------------------------------------------------
2020-04-26 07:03:39,990:INFO:------------------------------------------------------------------------------------------------
2020-04-26 07:31:11,367:INFO:------------------------------------------------------------------------------------------------
2020-04-26 07:53:14,078:INFO:------------------------------------------------------------------------------------------------
2020-04-26 08:03:44,705:INFO:------------------------------------------------------------------------------------------------
2020-04-26 08:31:13,597:INFO:------------------------------------------------------------------------------------------------
2020-04-26 08:53:14,498:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:03:49,670:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:20:46,974:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:31:15,788:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:53:14,827:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:55:30,859:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:30,859:INFO:7
2020-04-26 09:55:37,148:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:37,148:INFO:4
2020-04-26 09:55:37,386:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:37,386:INFO:7
2020-04-26 09:55:37,702:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:55:37,936:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:55:38,293:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:38,293:INFO:7
2020-04-26 09:55:38,567:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:38,567:INFO:4
2020-04-26 09:55:38,951:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:55:38,951:INFO:7
2020-04-26 09:56:03,611:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:56:03,612:INFO:7
2020-04-26 09:56:04,035:WARNING:Not Found: /favicon.ico
2020-04-26 09:56:06,416:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:56:07,559:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:56:07,559:INFO:2
2020-04-26 09:58:49,497:INFO:------------------------------------------------------------------------------------------------
2020-04-26 09:59:04,241:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 09:59:04,241:INFO:2
2020-04-26 09:59:04,725:WARNING:Not Found: /favicon.ico
2020-04-26 10:01:46,236:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:02:09,089:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:02:09,089:INFO:2
2020-04-26 10:02:09,488:WARNING:Not Found: /favicon.ico
2020-04-26 10:03:54,378:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:03:55,690:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:05:51,780:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:10:23,076:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:10:24,050:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:10:24,050:INFO:2
2020-04-26 10:10:24,328:WARNING:Not Found: /favicon.ico
2020-04-26 10:10:32,741:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:10:37,154:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:12:01,779:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:12:01,780:INFO:2
2020-04-26 10:12:03,457:WARNING:Not Found: /favicon.ico
2020-04-26 10:16:30,487:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:16:30,488:INFO:7
2020-04-26 10:16:30,693:WARNING:Not Found: /favicon.ico
2020-04-26 10:21:03,655:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:31:17,975:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:35:38,793:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:35:38,793:INFO:7
2020-04-26 10:35:39,132:WARNING:Not Found: /favicon.ico
2020-04-26 10:35:40,168:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:35:40,209:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:35:41,231:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:35:41,968:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:35:41,968:INFO:7
2020-04-26 10:35:51,215:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:35:52,528:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:35:54,111:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:36:23,414:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:36:25,982:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:36:27,534:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:36:44,395:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:36:44,396:ERROR:Internal Server Error: /prepaid
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 36, in getprepix
    numbertype = request.GET["numbertype"]
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'numbertype'"
2020-04-26 10:36:50,485:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:36:51,470:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:36:51,470:INFO:2
2020-04-26 10:36:54,521:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:36:58,268:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 10:38:42,624:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:38:44,150:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 10:38:44,150:INFO:2
2020-04-26 10:38:44,667:WARNING:Not Found: /favicon.ico
2020-04-26 10:38:44,678:WARNING:Not Found: /favicon.ico
2020-04-26 10:45:36,416:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:53:13,076:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:53:15,136:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:53:44,038:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:55:37,805:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:55:38,032:INFO:------------------------------------------------------------------------------------------------
2020-04-26 10:59:20,368:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:00:55,808:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:03:59,157:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:05:52,228:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:21:20,229:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:27:15,449:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:27:15,449:INFO:2
2020-04-26 11:27:23,238:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:27:23,239:INFO:2
2020-04-26 11:29:33,469:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:29:54,637:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:29:54,639:INFO:5000
2020-04-26 11:31:20,158:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:41:57,105:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:41:57,106:INFO:7
2020-04-26 11:41:57,479:WARNING:Not Found: /favicon.ico
2020-04-26 11:43:39,641:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:43:39,643:INFO:10000
2020-04-26 11:43:50,115:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:43:50,973:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:43:50,973:INFO:2
2020-04-26 11:43:56,008:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 11:44:03,955:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:45:36,570:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:47:37,625:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:47:37,625:INFO:2
2020-04-26 11:48:34,526:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:48:34,526:INFO:7
2020-04-26 11:49:08,596:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:49:08,599:INFO:10000
2020-04-26 11:50:20,574:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:50:20,574:INFO:7
2020-04-26 11:50:43,188:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:50:43,190:INFO:10000
2020-04-26 11:51:06,955:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:51:06,958:INFO:10000
2020-04-26 11:51:31,967:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:51:31,967:INFO:2
2020-04-26 11:51:32,341:WARNING:Not Found: /favicon.ico
2020-04-26 11:51:50,964:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:51:52,593:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:51:52,593:INFO:2
2020-04-26 11:51:52,832:WARNING:Not Found: /favicon.ico
2020-04-26 11:52:06,266:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:52:06,269:INFO:10000
2020-04-26 11:52:23,506:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:52:23,506:INFO:2
2020-04-26 11:52:28,002:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:52:28,003:INFO:2
2020-04-26 11:53:03,805:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:53:03,806:INFO:2
2020-04-26 11:53:13,397:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:53:15,547:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:54:48,004:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:55:04,499:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:55:04,500:INFO:2
2020-04-26 11:55:04,788:WARNING:Not Found: /favicon.ico
2020-04-26 11:55:04,851:WARNING:Not Found: /favicon.ico
2020-04-26 11:55:37,893:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:55:38,114:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:56:22,512:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:56:22,515:INFO:5000
2020-04-26 11:57:12,688:INFO:ДУГААРЫН ҮНЭ
2020-04-26 11:57:12,690:INFO:5000
2020-04-26 11:58:05,260:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:05,261:INFO:2
2020-04-26 11:58:06,186:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:58:08,229:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:08,229:INFO:7
2020-04-26 11:58:09,103:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:09,103:INFO:7
2020-04-26 11:58:19,388:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:19,389:INFO:7
2020-04-26 11:58:21,145:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:21,146:INFO:7
2020-04-26 11:58:22,507:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:22,508:INFO:7
2020-04-26 11:58:24,101:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:58:48,876:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:48,876:INFO:4
2020-04-26 11:58:50,472:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:58:50,472:INFO:4
2020-04-26 11:59:01,690:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:59:02,957:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:59:02,957:INFO:4
2020-04-26 11:59:03,933:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:59:03,933:INFO:4
2020-04-26 11:59:21,006:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:59:25,473:INFO:------------------------------------------------------------------------------------------------
2020-04-26 11:59:26,956:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:59:26,956:INFO:2
2020-04-26 11:59:51,431:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 11:59:51,432:INFO:2
2020-04-26 12:00:10,499:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:00:10,499:INFO:2
2020-04-26 12:00:11,347:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:00:11,348:INFO:2
2020-04-26 12:00:25,941:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:04:04,152:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:05:02,732:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:05:02,733:INFO:2
2020-04-26 12:05:03,001:WARNING:Not Found: /favicon.ico
2020-04-26 12:05:52,352:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:11:08,684:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:11:08,684:INFO:2
2020-04-26 12:11:14,045:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:11:14,045:INFO:2
2020-04-26 12:11:20,421:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:11:22,420:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:11:22,421:INFO:7
2020-04-26 12:12:00,725:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:12:00,725:INFO:7
2020-04-26 12:12:01,261:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:13:20,102:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:13:24,020:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:13:28,099:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:13:28,099:INFO:7
2020-04-26 12:13:36,888:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:13:36,889:INFO:7
2020-04-26 12:13:38,957:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:13:38,957:INFO:7
2020-04-26 12:14:02,297:INFO:ДУГААРЫН ҮНЭ
2020-04-26 12:14:02,301:INFO:5000
2020-04-26 12:15:00,183:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 212, in getNumber
    if data[1] == az:
IndexError: list index out of range
2020-04-26 12:15:16,438:INFO:ДУГААРЫН ҮНЭ
2020-04-26 12:15:16,441:INFO:10000
2020-04-26 12:15:48,969:INFO:ДУГААРЫН ҮНЭ
2020-04-26 12:15:48,972:INFO:5000
2020-04-26 12:15:58,881:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 12:16:03,452:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 12:16:40,863:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:16:42,122:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:16:42,122:INFO:2
2020-04-26 12:20:52,553:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:20:52,554:INFO:2
2020-04-26 12:21:36,816:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:21:57,683:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:21:59,641:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:21:59,642:INFO:7
2020-04-26 12:23:38,500:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:23:38,500:INFO:7
2020-04-26 12:23:49,354:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:23:49,354:INFO:7
2020-04-26 12:29:25,906:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:29:25,907:INFO:7
2020-04-26 12:31:22,295:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:40:37,644:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:40:38,357:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:40:38,358:INFO:7
2020-04-26 12:45:36,631:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:53:13,510:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:53:15,934:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:55:37,979:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:55:38,174:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:56:31,487:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:58:46,231:INFO:------------------------------------------------------------------------------------------------
2020-04-26 12:58:48,282:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 12:58:48,282:INFO:7
2020-04-26 12:58:48,528:WARNING:Not Found: /favicon.ico
2020-04-26 12:59:21,153:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:04:08,886:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:05:11,302:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:05:11,302:INFO:2
2020-04-26 13:05:12,263:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:05:12,264:INFO:2
2020-04-26 13:05:52,462:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:05:57,419:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:05:57,419:INFO:7
2020-04-26 13:07:11,351:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:07:11,351:INFO:7
2020-04-26 13:07:30,060:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:07:30,061:INFO:2
2020-04-26 13:07:31,132:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:07:59,305:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:07:59,306:INFO:7
2020-04-26 13:08:36,754:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:08:36,756:INFO:10000
2020-04-26 13:08:46,921:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:08:46,922:INFO:7
2020-04-26 13:09:01,696:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:09:04,591:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:09:04,591:INFO:2
2020-04-26 13:09:54,737:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:09:54,740:INFO:5000
2020-04-26 13:10:28,314:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 13:10:36,135:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:10:47,185:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:10:47,185:INFO:3
2020-04-26 13:10:57,699:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:10:59,094:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:10:59,094:INFO:2
2020-04-26 13:12:08,453:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:12:08,455:INFO:5000
2020-04-26 13:13:00,024:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:03,906:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:04,377:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:04,552:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:05,088:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:23,608:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,167:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,337:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,488:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,663:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,823:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:24,983:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:25,151:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:25,319:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:25,495:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:28,752:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:29,144:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:29,328:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:29,527:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:29,711:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:29,920:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:30,151:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:30,367:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:30,559:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:30,798:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:30,982:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:31,135:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:38,015:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:43,911:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:13:48,548:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 13:14:37,156:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:14:38,283:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:14:38,283:INFO:7
2020-04-26 13:14:47,391:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:14:49,155:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:14:49,156:INFO:2
2020-04-26 13:15:23,439:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:15:24,540:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:15:24,541:INFO:2
2020-04-26 13:16:06,106:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:16:06,107:INFO:7
2020-04-26 13:16:11,409:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:16:11,409:INFO:7
2020-04-26 13:16:23,106:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:16:23,106:INFO:7
2020-04-26 13:16:23,565:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:16:23,567:INFO:5000
2020-04-26 13:16:42,628:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:16:42,628:INFO:7
2020-04-26 13:16:53,978:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:16:53,978:INFO:7
2020-04-26 13:17:08,233:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:17:08,233:INFO:7
2020-04-26 13:17:42,969:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:17:42,969:INFO:7
2020-04-26 13:18:29,033:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:18:29,033:INFO:7
2020-04-26 13:19:15,242:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 13:19:26,917:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:19:26,919:INFO:10000
2020-04-26 13:20:01,298:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 13:21:15,425:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:21:19,684:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:21:19,686:INFO:10000
2020-04-26 13:21:38,749:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 13:21:44,710:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:21:50,102:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:21:51,129:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:21:51,130:INFO:7
2020-04-26 13:21:53,397:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:22:01,447:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:22:02,435:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:22:07,030:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 13:22:08,885:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:22:08,885:INFO:7
2020-04-26 13:22:12,829:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:22:12,829:INFO:7
2020-04-26 13:22:15,061:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:22:15,061:INFO:7
2020-04-26 13:22:44,352:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:22:44,353:INFO:7
2020-04-26 13:23:34,738:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:23:34,739:INFO:7
2020-04-26 13:25:04,698:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:26:19,132:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:26:19,132:INFO:7
2020-04-26 13:26:19,603:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:26:19,603:INFO:7
2020-04-26 13:26:25,248:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:26:25,248:INFO:7
2020-04-26 13:26:26,475:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:26:26,476:INFO:7
2020-04-26 13:26:46,062:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:26:46,065:INFO:10000
2020-04-26 13:27:10,320:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:27:10,321:INFO:7
2020-04-26 13:28:29,303:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:28:29,303:INFO:7
2020-04-26 13:31:24,439:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:31:36,646:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 13:31:36,647:INFO:3
2020-04-26 13:31:36,862:WARNING:Not Found: /favicon.ico
2020-04-26 13:32:05,338:INFO:ДУГААРЫН ҮНЭ
2020-04-26 13:32:05,340:INFO:20000
2020-04-26 13:42:07,742:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:53:13,667:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:53:16,351:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:55:38,070:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:55:38,255:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:56:36,517:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:59:21,364:INFO:------------------------------------------------------------------------------------------------
2020-04-26 13:59:47,379:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:03:40,326:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:04:05,124:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:04:05,125:INFO:2
2020-04-26 14:04:13,666:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:06:53,744:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:06:57,579:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:06:57,579:INFO:7
2020-04-26 14:09:39,830:INFO:ДУГААРЫН ҮНЭ
2020-04-26 14:09:39,833:INFO:10000
2020-04-26 14:10:05,667:INFO:ДУГААРЫН ҮНЭ
2020-04-26 14:10:05,669:INFO:10000
2020-04-26 14:10:36,733:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:10:37,626:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:10:37,626:INFO:7
2020-04-26 14:10:44,963:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 14:10:47,983:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:11:14,763:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:11:15,424:INFO:ДУГААРЫН ҮНЭ
2020-04-26 14:11:15,427:INFO:10000
2020-04-26 14:12:12,164:INFO:ДУГААРЫН ҮНЭ
2020-04-26 14:12:12,167:INFO:10000
2020-04-26 14:12:55,834:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:12:55,834:INFO:7
2020-04-26 14:13:07,429:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:13:07,429:INFO:7
2020-04-26 14:13:17,263:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:13:17,263:INFO:7
2020-04-26 14:14:44,038:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:14:44,039:INFO:7
2020-04-26 14:14:50,684:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:14:50,685:INFO:7
2020-04-26 14:15:00,166:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:15:01,327:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:15:01,327:INFO:7
2020-04-26 14:15:16,969:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:15:16,970:INFO:7
2020-04-26 14:15:21,237:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:15:21,237:INFO:7
2020-04-26 14:15:44,136:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:15:44,136:INFO:7
2020-04-26 14:21:44,813:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:22:09,988:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:24:27,830:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:24:27,831:INFO:2
2020-04-26 14:24:30,971:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:24:30,971:INFO:2
2020-04-26 14:24:34,516:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:24:34,516:INFO:2
2020-04-26 14:25:07,337:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:28:25,449:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:28:32,447:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:28:32,448:INFO:7
2020-04-26 14:29:41,968:INFO:ДУГААРЫН ҮНЭ
2020-04-26 14:29:41,970:INFO:10000
2020-04-26 14:31:26,651:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:32:14,788:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:32:14,788:INFO:7
2020-04-26 14:32:15,092:WARNING:Not Found: /favicon.ico
2020-04-26 14:34:50,643:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:34:50,643:INFO:2
2020-04-26 14:38:53,001:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:38:53,002:INFO:7
2020-04-26 14:39:12,888:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:39:12,888:INFO:7
2020-04-26 14:39:40,369:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 14:39:40,369:INFO:7
2020-04-26 14:42:13,724:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:53:16,904:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:55:38,166:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:55:38,348:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:56:41,762:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:59:21,588:INFO:------------------------------------------------------------------------------------------------
2020-04-26 14:59:47,497:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:03:40,432:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:04:18,530:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:04:44,299:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:04:44,299:INFO:7
2020-04-26 15:04:58,158:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:04:58,158:INFO:7
2020-04-26 15:04:59,605:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:04:59,605:INFO:7
2020-04-26 15:05:00,862:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:05:00,862:INFO:7
2020-04-26 15:05:20,777:WARNING:Not Found: /
2020-04-26 15:10:48,158:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:15:23,827:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:15:23,827:INFO:7
2020-04-26 15:16:12,273:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:16:14,799:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:16:14,799:INFO:2
2020-04-26 15:17:20,032:INFO:ДУГААРЫН ҮНЭ
2020-04-26 15:17:20,034:INFO:5000
2020-04-26 15:17:42,434:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:17:42,434:INFO:7
2020-04-26 15:22:26,592:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:25:10,741:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:31:16,702:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:31:18,659:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:31:18,659:INFO:2
2020-04-26 15:31:18,907:WARNING:Not Found: /favicon.ico
2020-04-26 15:36:14,144:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:36:14,144:INFO:7
2020-04-26 15:36:44,611:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:36:44,611:INFO:7
2020-04-26 15:37:56,448:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:38:05,981:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:38:05,982:INFO:7
2020-04-26 15:38:20,844:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:38:20,845:INFO:7
2020-04-26 15:39:22,813:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:39:22,813:INFO:7
2020-04-26 15:42:20,018:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:48:01,424:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:48:20,593:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:48:20,593:INFO:3
2020-04-26 15:48:40,223:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:48:43,594:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 15:48:43,594:INFO:2
2020-04-26 15:50:01,085:INFO:ДУГААРЫН ҮНЭ
2020-04-26 15:50:01,087:INFO:5000
2020-04-26 15:50:15,540:INFO:ДУГААРЫН ҮНЭ
2020-04-26 15:50:15,542:INFO:5000
2020-04-26 15:50:30,302:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:53:17,356:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:55:38,257:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:55:38,432:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:56:47,067:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:59:21,795:INFO:------------------------------------------------------------------------------------------------
2020-04-26 15:59:47,586:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:02:17,737:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:02:17,737:INFO:3
2020-04-26 16:02:18,132:WARNING:Not Found: /favicon.ico
2020-04-26 16:03:40,490:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:04:23,512:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:06:51,283:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:07:16,644:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:07:17,728:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:07:17,728:INFO:2
2020-04-26 16:13:04,475:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:13:04,476:INFO:2
2020-04-26 16:13:06,367:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:13:06,368:INFO:2
2020-04-26 16:13:31,847:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:13:31,847:INFO:2
2020-04-26 16:14:42,542:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:14:42,542:INFO:2
2020-04-26 16:14:43,713:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:14:45,462:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:14:45,462:INFO:7
2020-04-26 16:14:46,701:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:14:46,701:INFO:7
2020-04-26 16:15:02,111:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:15:02,111:INFO:7
2020-04-26 16:15:28,132:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:15:28,132:INFO:7
2020-04-26 16:16:21,374:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:16:21,375:INFO:7
2020-04-26 16:16:25,268:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:16:25,268:INFO:7
2020-04-26 16:16:52,836:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:16:52,837:INFO:7
2020-04-26 16:16:53,865:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:16:56,567:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:16:56,567:INFO:2
2020-04-26 16:17:03,992:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:17:05,041:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:17:05,042:INFO:7
2020-04-26 16:20:58,197:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:22:43,168:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:25:13,406:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:25:19,354:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:25:19,354:INFO:7
2020-04-26 16:25:20,757:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:25:20,757:INFO:7
2020-04-26 16:25:22,102:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:25:22,103:INFO:7
2020-04-26 16:25:23,085:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:25:23,085:INFO:7
2020-04-26 16:26:28,309:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:26:32,988:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:26:32,988:INFO:2
2020-04-26 16:30:54,228:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:31:02,467:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:31:02,467:INFO:2
2020-04-26 16:31:05,856:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:31:05,857:INFO:2
2020-04-26 16:31:07,496:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:31:07,496:INFO:2
2020-04-26 16:31:07,793:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:31:07,793:INFO:2
2020-04-26 16:31:28,089:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:31:28,089:INFO:2
2020-04-26 16:33:59,659:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:33:59,659:INFO:2
2020-04-26 16:34:17,914:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:34:17,915:INFO:2
2020-04-26 16:35:05,224:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:35:05,224:INFO:2
2020-04-26 16:35:27,845:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:35:27,845:INFO:2
2020-04-26 16:35:54,997:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:35:54,997:INFO:2
2020-04-26 16:36:33,089:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:36:33,089:INFO:2
2020-04-26 16:36:42,934:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:36:42,934:INFO:2
2020-04-26 16:36:44,008:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:36:46,676:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:36:46,677:INFO:2
2020-04-26 16:37:56,949:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:38:03,147:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:38:03,149:INFO:5000
2020-04-26 16:39:09,207:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:39:39,820:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:39:39,820:INFO:2
2020-04-26 16:41:19,860:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:41:19,862:INFO:10000
2020-04-26 16:41:33,365:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:41:33,367:INFO:10000
2020-04-26 16:44:40,140:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:45:11,450:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:45:11,450:INFO:2
2020-04-26 16:45:12,165:WARNING:Not Found: /favicon.ico
2020-04-26 16:45:37,524:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:45:37,524:INFO:2
2020-04-26 16:45:38,630:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:45:38,630:INFO:2
2020-04-26 16:45:39,334:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:45:39,335:INFO:2
2020-04-26 16:45:46,200:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:45:46,203:INFO:10000
2020-04-26 16:45:54,790:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:45:54,790:INFO:2
2020-04-26 16:46:05,719:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 16:46:54,715:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:46:57,581:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:46:57,582:INFO:2
2020-04-26 16:48:37,005:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:48:37,007:INFO:5000
2020-04-26 16:50:32,748:INFO:ДУГААРЫН ҮНЭ
2020-04-26 16:50:32,751:INFO:5000
2020-04-26 16:50:50,703:INFO:ДУГААРЫН ZAHIALGA
2020-04-26 16:51:05,235:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 16:51:05,235:INFO:2
2020-04-26 16:51:28,269:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 16:51:36,600:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 123, in getNumber
    move = int(request.GET['move'])
  File "/usr/local/lib/python2.7/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'move'"
2020-04-26 16:52:50,954:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:53:17,781:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:56:51,790:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:57:29,576:INFO:------------------------------------------------------------------------------------------------
2020-04-26 16:57:29,672:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:04:28,311:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:06:51,458:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:17:13,977:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:17:13,977:INFO:2
2020-04-26 17:17:33,384:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:17:33,384:INFO:2
2020-04-26 17:17:34,756:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:17:34,757:INFO:2
2020-04-26 17:20:58,445:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:21:04,077:INFO:ДУГААРЫН ҮНЭ
2020-04-26 17:21:04,080:INFO:5000
2020-04-26 17:22:55,985:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:22:55,985:INFO:2
2020-04-26 17:23:12,647:WARNING:Not Found: /favicon.ico
2020-04-26 17:25:16,272:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:28:49,666:INFO:ДУГААРЫН ҮНЭ
2020-04-26 17:28:49,669:INFO:5000
2020-04-26 17:37:57,233:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:38:37,884:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:38:37,885:INFO:7
2020-04-26 17:38:38,302:WARNING:Not Found: /favicon.ico
2020-04-26 17:38:43,634:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:50:48,126:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:50:49,440:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:50:49,440:INFO:2
2020-04-26 17:50:49,718:WARNING:Not Found: /favicon.ico
2020-04-26 17:50:57,296:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:50:58,653:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 17:50:58,654:INFO:7
2020-04-26 17:53:18,136:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:57:29,689:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:57:29,837:INFO:------------------------------------------------------------------------------------------------
2020-04-26 17:57:42,006:INFO:ДУГААРЫН ҮНЭ
2020-04-26 17:57:42,009:INFO:5000
2020-04-26 18:04:33,106:INFO:------------------------------------------------------------------------------------------------
2020-04-26 18:09:59,827:INFO:ДУГААРЫН ҮНЭ
2020-04-26 18:09:59,830:INFO:5000
2020-04-26 18:34:31,756:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:34:31,757:INFO:2
2020-04-26 18:35:32,507:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:35:32,507:INFO:2
2020-04-26 18:36:06,806:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:36:06,806:INFO:2
2020-04-26 18:37:57,464:INFO:------------------------------------------------------------------------------------------------
2020-04-26 18:40:37,826:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:40:37,827:INFO:2
2020-04-26 18:40:49,695:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:40:49,695:INFO:7
2020-04-26 18:43:59,578:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:43:59,578:INFO:7
2020-04-26 18:44:20,074:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:44:20,075:INFO:7
2020-04-26 18:44:42,106:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 18:44:42,107:INFO:7
2020-04-26 18:48:35,057:INFO:ДУГААРЫН ҮНЭ
2020-04-26 18:48:35,059:INFO:10000
2020-04-26 18:53:18,434:INFO:------------------------------------------------------------------------------------------------
2020-04-26 18:57:29,759:INFO:------------------------------------------------------------------------------------------------
2020-04-26 18:57:29,941:INFO:------------------------------------------------------------------------------------------------
2020-04-26 19:04:38,040:INFO:------------------------------------------------------------------------------------------------
2020-04-26 19:20:44,228:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 19:20:44,228:INFO:2
2020-04-26 19:20:44,427:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 19:20:44,427:INFO:2
2020-04-26 19:21:34,736:INFO:ДУГААРЫН ҮНЭ
2020-04-26 19:21:34,738:INFO:5000
2020-04-26 19:31:31,063:INFO:------------------------------------------------------------------------------------------------
2020-04-26 19:31:32,351:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 19:31:32,351:INFO:2
2020-04-26 19:37:57,718:INFO:------------------------------------------------------------------------------------------------
2020-04-26 19:40:59,628:WARNING:Not Found: /robots.txt
2020-04-26 19:53:18,770:INFO:------------------------------------------------------------------------------------------------
2020-04-26 20:01:59,588:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:01:59,588:INFO:7
2020-04-26 20:02:52,034:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:02:52,034:INFO:7
2020-04-26 20:03:05,866:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:03:05,867:INFO:7
2020-04-26 20:03:25,447:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:03:25,447:INFO:7
2020-04-26 20:03:27,355:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:03:27,356:INFO:7
2020-04-26 20:04:43,020:INFO:------------------------------------------------------------------------------------------------
2020-04-26 20:22:02,424:INFO:------------------------------------------------------------------------------------------------
2020-04-26 20:22:08,564:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:22:08,564:INFO:7
2020-04-26 20:22:27,724:ERROR:Internal Server Error: /getnumber
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/user/nFilterNew/controller/views.py", line 212, in getNumber
    if data[1] == az:
IndexError: list index out of range
2020-04-26 20:29:48,543:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:29:48,543:INFO:7
2020-04-26 20:30:03,955:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:30:03,955:INFO:7
2020-04-26 20:30:06,209:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:30:06,209:INFO:7
2020-04-26 20:30:29,757:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:30:29,757:INFO:7
2020-04-26 20:30:39,277:INFO:ДУГААРАА СОНГОЖ БУЙ ХЭСЭГ
2020-04-26 20:30:39,277:INFO:7
2020-04-26 20:37:57,996:INFO:------------------------------------------------------------------------------------------------
2020-04-26 20:53:19,580:INFO:------------------------------------------------------------------------------------------------
2020-04-26 21:04:47,936:INFO:------------------------------------------------------------------------------------------------
2020-04-26 21:34:14,804:WARNING:Not Found: /
2020-04-26 21:53:19,892:INFO:------------------------------------------------------------------------------------------------
2020-04-26 22:04:52,636:INFO:------------------------------------------------------------------------------------------------
2020-04-26 22:53:20,265:INFO:------------------------------------------------------------------------------------------------
2020-04-26 23:04:57,356:INFO:------------------------------------------------------------------------------------------------
2020-04-26 23:53:20,708:INFO:------------------------------------------------------------------------------------------------
2020-04-27 00:05:02,283:INFO:------------------------------------------------------------------------------------------------
2020-04-27 00:53:21,113:INFO:------------------------------------------------------------------------------------------------
2020-04-27 01:05:07,003:INFO:------------------------------------------------------------------------------------------------
2020-04-27 01:53:21,607:INFO:------------------------------------------------------------------------------------------------
2020-04-27 02:05:11,714:INFO:------------------------------------------------------------------------------------------------
2020-04-27 02:53:22,141:INFO:------------------------------------------------------------------------------------------------
2020-04-27 03:05:16,622:INFO:------------------------------------------------------------------------------------------------
2020-04-27 03:53:22,584:INFO:------------------------------------------------------------------------------------------------
2020-04-27 04:05:21,357:INFO:------------------------------------------------------------------------------------------------
2020-04-27 04:53:23,013:INFO:------------------------------------------------------------------------------------------------
2020-04-27 05:05:26,120:INFO:------------------------------------------------------------------------------------------------
2020-04-27 05:53:23,295:INFO:------------------------------------------------------------------------------------------------
2020-04-27 06:05:30,892:INFO:------------------------------------------------------------------------------------------------
